joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_pan_joint
  pid: {p: 100.0, i: 0.01, d: 18.0}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_lift_joint
  pid: {p: 280.0, i: 10.0, d: 20.0}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: elbow_joint
  pid: {p: 180.0, i: 1.0, d: 18.0}

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_1_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_2_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: wrist_3_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
